[tool.poetry]
name = "py1"
version = "0.1.0"
description = ""
authors = ["james <james@oki001.xyz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
web3 = "^6.0.0b2"
requests = "^2.28.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
